# Generated by Django 4.0.3 on 2022-05-08 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20210619_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
