# Generated by Django 4.0.3 on 2022-05-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_user_voitureasoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_cashier',
            field=models.BooleanField(default=True),
        ),
    ]
