# Generated by Django 4.0.3 on 2022-05-10 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_alter_user_is_cashier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_cashier',
            new_name='is_normal',
        ),
    ]
